# .github/workflows/pages.yml
name: Deploy Pages (static)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # falls du baust (z.B. Vite): npm ci && npm run build -> artefakt in ./dist
      # hier: statisch in ./docs
      - run: echo ok
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

